# Generated by Django 5.0.4 on 2024-05-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=85)),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=250)),
            ],
        ),
    ]
